Repository brunonavarro/DragAndDropCompose, pull requests merged in 2023-04, with the labels that each got.

#9 7 independizar logica de libreria parte 01
  .idea/copyright/BrunoDanielNavarroNuñez.xml
  .idea/copyright/profiles_settings.xml
  .idea/vcs.xml
  app/src/main/java/com/nsoft/comunityapp/draganddrop/MainActivity.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/MainViewModel.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/components/DragDropScreen.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/DragItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/PersonUIItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/library/DragAndDrop.kt
Labels: refactor

#10 Funciones y Clases Genéricas al 90%
  .idea/copyright/BrunoDanielNavarroNuñez.xml
  .idea/copyright/profiles_settings.xml
  .idea/vcs.xml
  app/src/main/java/com/nsoft/comunityapp/draganddrop/MainActivity.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/MainViewModel.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/components/DragDropScreen.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/DragItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/PersonUIItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/library/DragAndDrop.kt
Labels: toProd

#11 Fix: Refactorizando funciones que acepten datos genericos y separando…
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/components/DragDropScreen.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/DragItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/library/DragAndDrop.kt
Labels: refactor

#12 Develop
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/components/DragDropScreen.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/DragItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/library/DragAndDrop.kt
Labels: toProd

#14 New: se agrega efecto de item en blanco cuando está siendo arrastrado.
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/MainViewModel.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/components/DragDropScreen.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/DragItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/library/DragAndDrop.kt
Labels: issue

#16 creacion de interface y validando que compila
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/components/DragDropScreen.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/entities/DragItem.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/library/DragAndDrop.kt
Labels: refactor

#18 Solve generic column component
  app/src/main/java/com/nsoft/comunityapp/draganddrop/MainActivity.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomDragCard.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/CustomHeaderColumn.kt
  app/src/main/java/com/nsoft/comunityapp/draganddrop/ui/library/DragAndDrop.kt
Labels: refactor, release
